CREATE TABLE jugador (
  id BIGINT NOT NULL AUTO_INCREMENT,
  dorsal INT NOT NULL,
  posicion VARCHAR(50) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
  capitan TINYINT(1) NOT NULL DEFAULT 0,
  imagen VARCHAR(255) CHARACTER SET utf32 COLLATE utf32_unicode_ci DEFAULT NULL,
  id_usuario BIGINT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_unicode_ci;
